export enum ActionType {
  DOWNLOADED_CARDS_FROM_CART = "DOWNLOADED_CARDS_FROM_CART",
  ADDED_TO_CART = "ADDED_TO_CART",
  REMOVED_FROM_CART= "REMOVED_FROM_CART",
  PURCHASED_PRODUCTS = "PURCHASED_PRODUCTS"
}
