export enum ActionType {
  DOWNLOAD_ALL_CARDS_REQUESTED = "DOWNLOAD_ALL_CARDS_REQUESTED",
  DOWNLOAD_ALL_CARDS_SUCCESS = "DOWNLOAD_ALL_CARDS_SUCCESS",
  DOWNLOAD_ALL_CARDS_ERROR = "DOWNLOAD_ALL_CARDS_ERROR",
}


